### ISSUE TITLE
Bad cursor placement in atom 1.1

### ISSUE THREAD

**Issue by daslicious** [jesseweed/seti-syntax#106]
the cursor placement is jacked.

https://github.com/atom/atom/issues/9335#issuecomment-152362872

**Comment by kogai** [comment]
For reference, It was resolved by the following work -around. 

open `~/.atom/packages/seti-syntax/styles/editor.scss`
then, comment out two properties.
```scss
  .line.cursor-line {
    background: @selected-line !important;
    // padding-left: 10px;
    // margin-left: -10px;
  }
```
