### ISSUE TITLE
Python unreadable after last update

### ISSUE THREAD

**Issue by OmgImAlexis** [jesseweed/seti-syntax#123]
The first screenshot is a sample of code from about a month ago, I just updated to the latest version of seti-ui and seti-syntax and now most of my files are almost unreadable. Is there anyway to get them close to how they use to be or will I need to manually install an older version of this?

![screen shot 2016-04-25 at 1 21 28 pm](https://cloud.githubusercontent.com/assets/6525926/14985196/8d0ff2ec-1185-11e6-8af1-6967fca3371e.png)
![screen shot 2016-05-03 at 11 18 59 pm](https://cloud.githubusercontent.com/assets/6525926/14985195/8c8539e0-1185-11e6-922b-a6b93bb71d6b.png)

**Comment by jesseweed** [comment]
Hrm, that is a lot of blue. I'll take a look at it.

**Comment by justinaray** [comment]
@jesseweed I had a similar problem with markdown files and the new themes.

I "fixed" it by overridding the `.source` style in my stylesheet to a neutral gray that will be overridden by keyword styling.  Seems to help with languages that are considered source but don't have many keywords.

Not sure if this helps here, you have a better suggestion, or the theme could be less aggressive on styling source selectors.

**Comment by onewhaleid** [comment]
I am having the same problem (python, seti-syntax 1.0.1)

**Comment by Gaff** [comment]
Glad it's not just me!

@justinaray what exactly did you put in your styles? I have this but it didn't work:

```
.source {
  color: #D3D3D3;
}
```

**Comment by justinaray** [comment]
@Gaff You didn't post the entire block, but I'm betting your rule is not specific enough to override the defaults.  In essence, my stylesheet looks like this:

```less
atom-workspace.theme-seti-syntax {
    // ...
    atom-text-editor::shadow {

        // ***** Seti Tweaks *****

        // Mute the default source color unless it's a keyword
        // Helps with keyword-light langs like markdown
        .source {
            color: #babebd;
        }
        // ...
    }
    // ...
}
```
