### ISSUE TITLE
Bracket matcher not working as intended

### ISSUE THREAD

**Issue by GU5TAF** [jesseweed/seti-syntax#25]
![screenshot 2014-12-10 11 12 19](https://cloud.githubusercontent.com/assets/3854323/5374187/7b7ebe56-805d-11e4-98fa-feb4d125442c.png)
The bracket matcher classes appear to have changed, I fixed the issue temporarily by putting the following in my stylesheet:

``` less
.theme-seti-syntax {
  .bracket-matcher {
    border: 0;
    margin: 0;
    > .region {
      border-bottom: 1px solid #55b5db;
      margin-top: 2px;
    }
  }
}
```
