### ISSUE TITLE
Can't override selected text.

### ISSUE THREAD

**Issue by curtisblackwell** [jesseweed/seti-syntax#29]
The way the borders on multi-line selected text make it a little harder to read text, so I'm trying to override it. I found the LESS that sets the border, but I can't seem to override it with my styles.less override.

It should be:

```less
.editor, :host {
  .selection .region { border: 0; }
}
```

…but it doesn't work. Not even with `!important`. Any ideas?
