### ISSUE TITLE
Support for JS template strings

### ISSUE THREAD

**Issue by artiifix** [jesseweed/seti-syntax#64]
Since ES6, there are tmplate strings surrounded by back-ticks (`` ` ``). I think the `${...}` and the code inside should get a different colour than the string. The markup for `` `text${code}text` `` as generated by Atom looks like this:
```html
<span class="string quoted template js">
    <span class="punctuation definition string begin js">`</span>
    text
    <span class="source js embedded source">
        <span class="punctuation section embedded js">${</span>
        code
        <span class="punctuation section embedded js">}</span>
    </span>
    text
    <span class="punctuation definition string end js">`</span>
</span>
```

I would implement this myself, but sadly I don't know what colour to use etc.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings for the specs.

**Comment by brettz9** [comment]
I had the same concern for another theme and came across this issue.

Haven't looked carefully at the source for this theme, but in the stylesheet you can do this (to get the embedded expression the same color as this theme's `${` and `}`, i.e., pink):

```less
atom-text-editor::shadow, :host {
  .js.embedded.source {
    color: pink;
  }
```

Here is a more detailed look and some sample colors so you can distinguish within a template.

```less
atom-text-editor::shadow, :host {
  .source.js {
    .string.quoted.template.js {
      color: red;
      .source.js.embedded.source {
        color: blue;
        &.punctuation.section.embedded {
          color: #a3685a;
        }
      }
    }
  }
}
```
